### ISSUE TITLE
Can someone explain the snowplow url this plugin post to?

### ISSUE THREAD

**Issue by sunshineo** [snowplow-incubator/snowplow-google-analytics-plugin#16]
Specifically this line
```
    var path = ((endpoint.substr(-1) !== '/') ? endpoint + '/' : endpoint) + vendor + '/' + version;
```

I cannot find any documentation talk about the url in the form of /vendor/version . I found some code here https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/adapters/AdapterRegistry.scala but it seems to be the enrichment in later stage

**Comment by BenFradet** [comment]
Hello, please raise your community support questions in [our Discourse forum](https://discourse.snowplowanalytics.com/) more people will be able to help you there.

That's how we determine which adapter to use here GA.
