### ISSUE TITLE
Add Google Tag Manager instructions to the Readme

### ISSUE THREAD

**Issue by sahava** [snowplow-incubator/snowplow-google-analytics-plugin#8]
Google Tag Manager doesn't support plugins in Universal Analytics tag templates :(

That leaves the option of using a Custom HTML tag to setup GA tracking, but the problem is that all tags need to be setup to use the same tracker name as in the Custom HTML tag, and setting the tracker name in GTM has its own host of problems (https://www.simoahava.com/gtm-tips/be-careful-with-the-tracker-name-setting/).

So the best (in my view) solution currently is to not use a plugin at all but just configure `customTask` to do the very same thing.

1) Create a **Custom JavaScript Variable**, name it "customTask - Snowplow duplicator", and add the following code within:

```
function() {
  // Change this to reflect your collector endpoint
  var endpoint = 'https://some-pixel-endpoint/i';

  return function(model) {
    var vendor = 'com.google.analytics';
    var version = 'v1';
    var path = ((endpoint.substr(-1) != '/') ? endpoint + '/' : endpoint) + vendor + '/' + version;

    var globalSendTaskName = '_' + model.get('trackingId') + '_sendHitTask';

    var originalSendHitTask = window[globalSendTaskName] = window[globalSendTaskName] || model.get('sendHitTask');
    model.set('sendHitTask', function(sendModel) {
      var payload = sendModel.get('hitPayload');
      originalSendHitTask(sendModel);
      var request = new XMLHttpRequest();
      request.open('POST', path, true);
      request.setRequestHeader("Content-type", "text/plain; charset=UTF-8")
      request.send(payload);
    });
  };
}
```

2) In **all** your GA tags in GTM, browse to **Fields to set** (by either using a Google Analytics Settings variable or checking "Enable overriding settings for this tag") and add the following field:

**Field name**: customTask
**Value**: {{customTask - Snowplow duplicator}}

Now any tag that has this field set will duplicate the hit to the Snowplow collector.

The downside of this solution is how to maintain it if you update e.g. `vendor` or `version` values. If it's unlikely that these change, then this solution would be quite robust. On the other hand, if these values are particularly volatile, then some other method must be introduced, such as a preliminary library download which offers the `customTask` as a global variable you can reference in the Custom JS variable, or something similar?

**Comment by BenFradet** [comment]
Thanks for the explanation, would you mind tuning this issue into a PR incorporating your explanation into the readme?

btw, `vendor` and `version` are unlikely to change for a long time.

**Comment by sahava** [comment]
Hey Ben,

PR created: #9
